version: "3.9"
services:
  bot:
    build: .
    container_name: tournament_bot
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./bot_logs:/app/logs
      - type: bind
        source: ./discord_token.txt
        target: /app/discord_token.txt
        read_only: true
    # If you want to see the bot's logs in real time, you can also set "tty: true" or "stdin_open: true" here.
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongo_data
        target: /data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
